spring.application.name=QUESTIONSERVICE
server.port = 9082

spring.datasource.url = jdbc:mysql://localhost:3306/microservice
spring.datasource.username = root
spring.datasource.password = 1234
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto =update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Micrometer + Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*

logging.pattern.console=%d{HH:mm:ss} [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n

#management.server.port=9082

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost


