spring.application.name=APIGATEWAY

server.port=8083
spring.cloud.gateway.routes[0].id=QUIZSERVICE
spring.cloud.gateway.routes[0].uri=lb://QUIZSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/quiz/**,/quiz-test/**

spring.cloud.gateway.routes[1].id=QUESTIONSERVICE
spring.cloud.gateway.routes[1].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/question/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Micrometer + Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
logging.pattern.console=%d{HH:mm:ss} [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost





